apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "seiri-kube-agent.fullname" . }}
  labels:
    {{- include "seiri-kube-agent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "seiri-kube-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "seiri-kube-agent.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "seiri-kube-agent.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SEIRI_BACKEND_URL
              value: {{ .Values.seiri.backendUrl | quote }}
            - name: SEIRI_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "seiri-kube-agent.fullname" . }}-auth
                  key: token
            - name: CLUSTER_ID
              value: {{ .Values.seiri.clusterId | quote }}
          ports:
            - name: health
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: health
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: health
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
