apiVersion: v1
kind: Secret
metadata:
  name: {{ include "seiri-kube-agent.fullname" . }}-auth
  labels:
    {{- include "seiri-kube-agent.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.seiri.authToken | b64enc }}
